MYSQL_URL=jdbc:mysql://mysql.railway.internal:3306/sakila
MYSQL_USER=root
MYSQL_PASSWORD=${{MySQL.MYSQLPASSWORD}}
ELASTICSEARCH_URI=http://elasticsearch.railway.internal:9200
JPA_DDL_AUTO=validate
PORT=8080